# ===============================
# Baza danych (PostgreSQL)
# ===============================

# Dla wersji lokalnej (po??czenie z kontenerem Docker przez localhost:5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/coursemanager

# Dla wersji uruchamiania Spring Boot wewn?trz Docker Compose:
# spring.datasource.url=jdbc:postgresql://postgresql:5432/coursemanager

spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ta linia nie jest potrzebna, ale mo?e zosta?:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Thymeleaf
# ===============================

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ===============================
# Spring Security
# ===============================

spring.main.allow-circular-references=true

# ===============================
# Logowanie
# ===============================

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG